### ISSUE TITLE
Spelling Mistake in the home page of the Website !

### ISSUE THREAD

**Issue by Patelmedhansh** [Patelmedhansh/MinorProject#5]
https://github.com/user-attachments/assets/cd594907-c575-48d9-957d-6400b4d19829

As we can see in the video, there Is an spelling error in the home page of website.
it should be studio.

**Comment by Tonnykimanthi** [comment]
Hey Patel! I hope you don't mind assigning me to fix the issue of spellings. Thank you!

**Comment by Patelmedhansh** [comment]
Hey @Tonnykimanthi  the issue is already solved. Thank you for interacting !
